import PDFDocument from 'pdfkit'
import fs from 'fs'
import path from 'path'

export interface VCAACurriculumData {
  title: string
  description: string
  content: string
  learningAreas: string[]
  capabilities: string[]
  foundationalSkills: string[]
  crossCurriculumPriorities: string[]
}

export class VCAACurriculumPDFGenerator {
  private doc: PDFDocument
  private outputPath: string

  constructor() {
    this.doc = new PDFDocument({
      margin: 50,
      size: 'A4',
      info: {
        Title: 'VCAA Curriculum F-10 Version 2.0',
        Author: 'Taughtful Education Platform',
        Subject: 'Victorian Curriculum and Assessment Authority Resources',
        Keywords: 'VCAA, curriculum, education, teaching, resources',
      },
    })

    this.outputPath = path.join(
      process.cwd(),
      'public',
      'resources',
      'vcaa-curriculum-complete-guide.pdf'
    )
  }

  private addHeader(title: string, level: number = 1) {
    this.doc
      .fontSize(level === 1 ? 20 : level === 2 ? 16 : 14)
      .text(title, { align: 'left' })
    this.doc.moveDown(0.5)
  }

  private addContent(text: string) {
    this.doc.fontSize(11).text(text, { align: 'justify', lineGap: 2 })
    this.doc.moveDown()
  }

  private addBulletList(items: string[]) {
    items.forEach((item) => {
      this.doc.fontSize(11).text('• ' + item, { continued: false })
    })
    this.doc.moveDown()
  }

  generateCurriculumPDF(data: VCAACurriculumData): Promise<string> {
    return new Promise((resolve, reject) => {
      const stream = this.doc.pipe(fs.createWriteStream(this.outputPath))

      stream.on('finish', () => {
        resolve(this.outputPath)
      })

      stream.on('error', reject)

      // Cover page
      this.doc
        .fontSize(24)
        .font('Helvetica-Bold')
        .text('Victorian Curriculum F-10', 50, 100, { align: 'center' })
      this.doc.fontSize(20).text('Version 2.0', 50, 130, { align: 'center' })
      this.doc
        .fontSize(16)
        .font('Helvetica')
        .text('Comprehensive Curriculum Guide', 50, 160, { align: 'center' })
      this.doc.moveDown(8)
      this.doc
        .fontSize(12)
        .text('Generated by Taughtful Education Platform', { align: 'center' })
      this.doc.addPage()

      // Table of Contents
      this.addHeader('Table of Contents', 1)
      this.addContent('1. Curriculum Overview')
      this.addContent('2. Learning Areas')
      this.addContent('3. Capabilities')
      this.addContent('4. Foundational Skills')
      this.addContent('5. Cross-Curriculum Priorities')
      this.addContent('6. Implementation Guidelines')
      this.doc.addPage()

      // Curriculum Overview
      this.addHeader('1. Curriculum Overview', 1)
      this.addContent(data.description)
      this.addContent(data.content)
      this.doc.addPage()

      // Learning Areas
      this.addHeader('2. Learning Areas', 1)
      this.addContent(
        'The Victorian Curriculum F-10 includes eight key learning areas:'
      )
      this.addBulletList(data.learningAreas)
      this.doc.addPage()

      // Capabilities
      this.addHeader('3. Capabilities', 1)
      this.addContent(
        'Four critical capabilities are integrated throughout the curriculum:'
      )
      this.addBulletList(data.capabilities)
      this.doc.addPage()

      // Foundational Skills
      this.addHeader('4. Foundational Skills', 1)
      this.addContent('Essential skills that underpin student learning:')
      this.addBulletList(data.foundationalSkills)
      this.doc.addPage()

      // Cross-Curriculum Priorities
      this.addHeader('5. Cross-Curriculum Priorities', 1)
      this.addContent(
        'Key priorities that are addressed across learning areas:'
      )
      this.addBulletList(data.crossCurriculumPriorities)
      this.doc.addPage()

      // Implementation Guidelines
      this.addHeader('6. Implementation Guidelines', 1)
      this.addContent(
        'This curriculum is designed to be flexible and adaptable to meet the needs of all students. Teachers should:'
      )
      this.addBulletList([
        'Use the curriculum as a framework for planning teaching and learning programs',
        'Adapt content to meet local contexts and student needs',
        'Integrate capabilities across learning areas',
        'Use achievement standards to monitor student progress',
        'Collaborate with colleagues to share best practices',
      ])

      this.doc.end()
    })
  }

  static getSampleCurriculumData(): VCAACurriculumData {
    return {
      title: 'VCAA Curriculum F-10 Version 2.0',
      description:
        'The Victorian Curriculum F-10 provides a single, coherent and comprehensive set of content descriptions and associated achievement standards to enable teachers to plan, monitor, assess and report on the learning achievement of every student.',
      content:
        'Version 2.0 represents a significant update to the curriculum, focusing on contemporary learning needs, digital literacy, and preparing students for future challenges. The curriculum is structured around learning areas, capabilities, foundational skills, and cross-curriculum priorities.',
      learningAreas: [
        'The Arts (Dance, Drama, Media Arts, Music, Visual Arts, Visual Communication Design)',
        'English',
        'Health and Physical Education',
        'Humanities (Civics and Citizenship, Economics and Business, Geography, History)',
        'Languages',
        'Mathematics',
        'Science',
        'Technologies (Design and Technologies, Digital Technologies)',
      ],
      capabilities: [
        'Critical and Creative Thinking',
        'Ethical Capability',
        'Intercultural Capability',
        'Personal and Social Capability',
      ],
      foundationalSkills: ['Digital Literacy', 'Literacy', 'Numeracy'],
      crossCurriculumPriorities: [
        'Aboriginal and Torres Strait Islander Histories and Cultures',
        "Asia and Australia's Engagement with Asia",
        'Sustainability',
      ],
    }
  }
}
